### ISSUE TITLE
Another C Submission

### ISSUE THREAD

**Issue by presentfactory** [ISSOtm/1234-golf#5]
Saw this from someone I know so I thought I'd try my hand at it, this is what I ended up with:

```
a,b; // Initialize a/b to 0

main() {
  ++a; // Generate 1
  b = a <<= a + a; // Generate 4 from 1 << 2 or 1 << (1 + 1), store to a/b
  b *= a + a + a; // Generate 48 from 4 * 12 or 4 * (4 + 4 + 4), store to b

  while (a--) // Loop 4 times
    putchar(++b); // Print out characters starting from ASCII 41
}
```

Which when compacted is 58 characters:
`a,b;main(){++a;b=a<<=a+a;b*=a+a+a;while(a--)putchar(++b);}`

Note that compiles fine in a C compiler like gcc/clang if one actually tells it the language is C (the online compiler you linked on the project page assumes the code is C++ due to the extension) since types on global variables are not required (unlike in ISO C++ apparently). This can be seen [here](https://wandbox.org/permlink/6gN1wHLGej9ik1H4) (also note that this code has no undefined behavior unlike some of the other submissions, only warnings due to the horrid language hacks for default int in various contexts as expected).

If that's not acceptable then this should be fine as 62 characters, but it shouldn't need to be this way in C as mentioned before:
`int a,b;main(){++a;b=a<<=a+a;b*=a+a+a;while(a--)putchar(++b);}`

**Comment by ISSOtm** [comment]
Nice! Do you want to submit a PR, or should I submit this myself?
Also, possible optimization: is there anywhere in the `b = a <<= a + a;` line where you could put the `++a`?

**Comment by presentfactory** [comment]
@ISSOtm You'd think so but no because that'd invoke undefined behavior in C since there are no sequence guarantees in contexts like that. In C++17 it would be fine to put it somewhere I think but then the default int globals wouldn't work like I said, meaning more characters would be introduced to fix that so that's just unfortunate. You can find details of that though [here](https://en.cppreference.com/w/c/language/eval_order).

If that wasn't the case then something like this would work:
``a,b;main(){b=a<<=++a+a;b*=a+a+a;while(a--)putchar(++b);}``

Also you can submit it.
